# Core with Redis emulation
db:
  redis:
    emulate: true
    namespace: EG

crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

session:
  secret: keyboard_cat_change_in_production
  resave: false
  saveUninitialized: false

accessTokens:
  timeToExpiry: 7200000

refreshTokens:
  timeToExpiry: 7200000

authorizationCodes:
  timeToExpiry: 300000